export const metadata = {
  title: "Next Starter",
  description: "Generated by ChatGPT",
};

import "./globals.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
